### ISSUE TITLE
docs: Changes to migrate from tfsec to trivy

### ISSUE THREAD

**Issue by AnaisUrlichs** [aquasecurity/tfsec#2016]
This issue details any additional work/changes that have to be done to ensure the migration from trivy to tfsec is visible across repositories.

**Work done:**
- @simar7 already created this migration guide: https://github.com/aquasecurity/tfsec/pull/1961/files

**Goals**
- migration guide has to become more visible in the docs, the Readme, and tfsec -related projects
https://github.com/aquasecurity/tfsec/pull/1961
- it has to be clear why the changes are happening, how users will be affected, what they can do next

**Todo:**
- [x] Update Readme with information on the future of tfsec and the migration guide, so it is the first thing that people see https://github.com/aquasecurity/tfsec 
- [x] Update the starting page of the docs https://aquasecurity.github.io/tfsec/v1.28.1/ 
- [ ] Link the guide in the tfsec channel on Slack

**Thought**: Making it a banner beyond those main pages, detailing the key information so that people see it no matter which docs they click on
e.g. with this plugin we could create banners https://timvink.github.io/mkdocs-print-site-plugin/how-to/banner.html
I haven't found a way that mkdocs does it out-of-the-box

**Projects related to tfsec that have to be updated**
- [x] https://github.com/aquasecurity/tfsec-pr-commenter-action
- [x] https://github.com/aquasecurity/tfsec-action
- [ ] https://github.com/aquasecurity/intellij-tfsec
- [ ] https://github.com/aquasecurity/tfsec-chocolatey
- [ ] https://github.com/aquasecurity/vscode-tfsec
- [ ] https://github.com/aquasecurity/tfsec-sarif-action
- [ ] https://github.com/aquasecurity/tfsec-azure-pipelines-task
- [ ] https://github.com/aquasecurity/vim-tfsec
- [ ] https://github.com/aquasecurity/cloud-metadata (? this one too ?)

**Questions**
1. Should we add the migration guide also to the trivy docs: under tutorials https://aquasecurity.github.io/trivy/v0.38/tutorials/overview/
2. Ask Colin (social media guru at Aqua) who has access to the tfsec Twitter account https://twitter.com/tfsec_dev -- so that we can make an announcement from the twitter account e.g. one last tweet

cc @giorod3

**Comment by AnaisUrlichs** [comment]
Copies for a banner on the repo could have the following copy or similar:
All of our scanning-related efforts have moved to one place, and that is Trivy. Please look at the [migration guide](link to guide) and the Trivy [docs] (link to Trivy docs) for further information.

**Comment by simar7** [comment]
You could look into "archiving a repo" natively with GitHub https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

**Comment by AnaisUrlichs** [comment]
but do we want to have the repo properly archived right away? I believe @giorod3 said that people should still be able to use tfsec until they switch over etc. & @itaysk did not want to do that a while ago -- thoughts now?
we should do that eventually I believe

**Comment by wyardley** [comment]
Is there still going to be a final dependencies update as promised, or will there just be a release with #2067?

**Comment by simar7** [comment]
Closing as there's no actionable items on this issue.
